language: java

sudo: false

env:
  - VIRTUALBOX_UNAVAILABLE=true

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pjeemi-maven-plugin
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pjeemi-components

script:
- mvn verify -B -V -Pjeemi-maven-plugin -Pjeemi-components -Pjeemi-coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
