# https://github.com/codecov/example-java

language: java

sudo: false # faster builds

env:
  - VIRTUALBOX_UNAVAILABLE=true

services:
- docker

after_success:
- bash <(curl -s https://codecov.io/bash)
